# Generated by Django 2.0.7 on 2018-08-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('segment', models.CharField(max_length=100)),
                ('lob', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('organizationEmployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsMatrixApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=150)),
                ('technology', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('lastModifiedByID', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='skillsMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(max_length=100)),
                ('levelOfInterest', models.CharField(max_length=100)),
                ('skillsMatrixEmployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsMatrixApp.employee')),
                ('skillsMatrixSkills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsMatrixApp.skills')),
            ],
        ),
    ]
