# Generated by Django 2.0.7 on 2018-08-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsMatrixApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'employee'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name_plural': 'organization'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'skills'},
        ),
        migrations.AlterModelOptions(
            name='skillsmatrix',
            options={'verbose_name_plural': 'skillsMatrix'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstName',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastName',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='dateModified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='lastModifiedByID',
            field=models.CharField(max_length=10, verbose_name='Last Modified By'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skillName',
            field=models.CharField(max_length=150, verbose_name='Skill Name'),
        ),
        migrations.AlterField(
            model_name='skillsmatrix',
            name='levelOfInterest',
            field=models.CharField(max_length=100, verbose_name='Level Of Interest'),
        ),
    ]
